apiIssueGET:
  path: /api/issue/{id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\GetController' }
  methods:  [GET]
  requirements:
    id:  \d+

apiIssueSave:
  path: /api/issue
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\SaveController' }
  methods:  [POST]

apiIssueUpdate:
  path: /api/issue/{id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\UpdateController' }
  methods:  [POST]
  requirements:
    id:  \d+

apiIssueWorklog:
  path: /api/issue/{id}/worklog
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\WorklogController' }
  methods:  [POST]
  requirements:
    id:  \d+

apiIssueSearch:
  path: /api/issue/search
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\SearchController' }
  methods:  [GET]

apiIssueMetadataGET:
  path: /api/issue/metadata
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\MetadataController' }
  methods:  [GET]

apiProjectGET:
  path: /api/project/{code}
  defaults: { _controller: '\Ubirimi\Api\Controller\Project\GetController' }
  methods:  [GET]

apiUserGET:
  path: /api/user/{username}
  defaults: { _controller: '\Ubirimi\Api\Controller\User\GetController' }
  methods:  [GET]

apiUserGETByFilters:
  path: /api/user
  defaults: { _controller: '\Ubirimi\Api\Controller\User\GetByFiltersController' }
  methods:  [POST]

apiUserAuthenticate:
  path: /api/user/authenticate
  defaults: { _controller: '\Ubirimi\Api\Controller\User\AuthenticateController' }
  methods:  [POST]

apiInstallClient:
  path: /api/client/save
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\SaveController' }
  methods:  [POST]

apiClientUpdateProfile:
  path: /api/client/update/profile
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\UpdateProfileController' }
  methods:  [POST]

apiGetAllClients:
  path: /api/client/all
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\GetAllController' }
  methods:  [GET]

apiGetClientById:
  path: /api/client/{id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\GetController' }
  methods:  [GET]
  requirements:
    id:  \d+

apiClientValidateDomain:
  path: /api/client/validate/domain/{domain}
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\ValidateDomainController' }
  methods:  [GET]

apiSharedGetCountries:
  path: /api/shared/countries
  defaults: { _controller: '\Ubirimi\Api\Controller\Shared\GetCountriesController' }
  methods:  [GET]

